---
title: "Rmarkdown_HW_Apr26"
author: "Rongkui Han"
date: "April 25, 2017"
output: 
  html_document: 
    keep_md: yes
---
####3.1.1
```{r}
library(tidyverse)
```
####3.2.1-3
```{r}
ggplot2::mpg
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

####3.2.4
```{r}
ggplot(data = mpg)
#I see an empty space
mtcars
#mtcars has 32 rows and 11 columns.
?mpg
#drv indicate what kind of "drive" a motor vehicle is. It can be a front-wheel drive (f), a rear wheel drive ("r") or a four wheel drive ("4").
ggplot(data = mpg) +
  geom_point(mapping = aes(x = hwy, y = cyl))
ggplot(data = mpg) +
  geom_point(mapping = aes(x = class, y = drv))
#The class vs drv plot is not informative because a lot of dots overlapped on top of each other, resulting in great loss of information. 
```
####3.3
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
## It is generally not advicable to use an ordered aesthetics (e.g. size) for an unordered variable (e.g. class)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
## SUV class disappeared because ggplot can only do 6 shapes at a time. 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
## make sure this time the "color = " argument is not in the aes() brackets. Or color will appear as a varieble with a legend the says "blue".)
```

####3.3.1
```{r}
#1. The code 
#ggplot(data = mpg) + 
#  geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))
#is wrong because the color = argument went inside the aes() bracket.

#2. 
#Categorical variables are :"manufacturer", "model", "trans", "drv", "fl"           and "class". Continuous variables are "displ", "year", "cyl", "cty" and "hwy".    
#I can see the class of each variable when I run ggplot2::mpg. The class of each variable (character, integer etc.) appears in "<>"'s underneath the names of the variables.

#3.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = year))
#The color has a gradient. 

#4. 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = hwy))
```

